name: Github Pages Deploy

on:
  push:
    branches:
      - main
    paths: [
      'src/**',
      'public/**',
      '**/package*.json',
      '**workflows/**.yml'
    ] 
  
  workflow_dispatch:

permissions: write-all # Required for the GitHub Pages action to deploy

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  Frontend-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Specify the Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build Vite-React app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
